[ros2]
enabled = true
camera_topic = "/camera/color/image_raw/compressed"
head_servos_command_topic = "/g1_comp_servo/cmd" # unitree_go/msg/MotoCmds
head_servos_state_topic = "/g1_comp_servo/state"
high_level_body_movements_topic = "/api/sport/request" # unitree_api/msg/Request

[detector]
enabled = true
yolo_model_path = "models/ball_yolov8.pt"
yolo_confidence_threshold = 0.7
rate = 10

[camera]
height = 480 #720
width = 640 #1280

[servos]
enabled = true
max_yaw = 45
max_pitch = 80
min_pitch = -20
kp = 0.08
dead_zone_px = 10
rate = 10

[body]
enabled = true
rate=10

