[ros2]
enabled = true
camera_topic = "/camera/color/image_raw/compressed"
head_servos_command_topic = "/g1_comp_servo/cmd" # unitree_go/msg/MotoCmds
head_servos_state_topic = "/g1_comp_servo/state"
high_level_body_movements_topic = "/api/sport/request" # unitree_api/msg/Request
audio_client_topic = "/api/voice/request" # unitree_api/msg/Request

# Labels of trained object
[classes.labels]
0 = "ball"
1 = "goal"
[classes.threshold]
0 = 0.7
1 = 0.7

[detector]
enabled = true
yolo_model_path = "models/ball_goal_yolov8_v2.pt"
yolo_confidence_threshold = 0.7
ball_close1_diameter = 65
ball_close2_diameter = 50
rate = 10

[camera]
height = 720
width = 1280

[servos]
enabled = true
max_yaw = 45
max_pitch = 80
min_pitch = -20
kp = 0.08
dead_zone_px = 10
rate = 10

[body]
enabled = true
caution_factor = 5 # 2: fast, 5: normal, 8: slow
rate = 10

[audio]
path = "sounds"
